#!/bin/sh
NANOBOT_URL="https://github.com/ontodev/nanobot.rs/releases/download/v2023-12-08/nanobot-x86_64-unknown-linux-musl"
if [ ! -f nanobot ]; then
  curl -L -o nanobot $NANOBOT_URL
  chmod +x nanobot
fi
if [ ! -f .nanobot.db ] || [ ! -s .nanobot.db ]; then
  ./nanobot init >> nanobot.log 2>&1
fi

# export GATEWAY_INTERFACE=CGI/1.1
# export REQUEST_METHOD=GET
# export PATH_INFO=/table
# export QUERY_STRING=""
./nanobot $@
