#!/bin/sh
NANOBOT_URL=https://github.com/ontodev/nanobot.rs/releases/download/v2023-11-30/nanobot-x86_64-unknown-linux-musl
if [ ! -f .nanobot.db ]; then
  if [ ! -f ../../nanobot ]; then
    curl -L -o ../../nanobot $(NANOBOT_URL)
    ../../nanobot init > /dev/null 2>&1
  fi
fi
../../nanobot $@
